apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "janusgraph.fullname" . }}
  labels:
    app: {{ template "janusgraph.name" . }}
    chart: {{ template "janusgraph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "janusgraph.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "janusgraph.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnvs }}
          env:
            {{- if .Values.bigTable.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp.json
            {{- end }}
              {{- with .Values.extraEnvs }}
                {{- toYaml . | trim | nindent 12 -}}
              {{- end }}
          {{- end }}
          ports:
            - containerPort: 8182
              protocol: TCP
          volumeMounts:
            {{- if .Values.BigTable.enabled }}
            - name: google-creds
              mountPath: /var/secrets/gcp.json
            {{- end }}
            - name: janusgraph-config
              mountPath: /janusgraph-config
            - name: local-db
              mountPath: {{ .Values.persistence.path }}
          livenessProbe:
            exec:
              command:
                - /tmp/healthcheck.py
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        {{- if .Values.bigTable.enabled }}
        - name: google-creds
          secret:
            name: {{ .Values.bigTable.serviceAccountSecret }}
        {{- end }}
        - name: janusgraph-config
          configMap:
            name: {{ .Values.configMapOverrideName | default ( printf "%s-config" .Release.Name ) }}
        - name: local-db
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "janusgraph.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
